id: P4D4F7C47
initial_creation_type: input
source_metadata:
  title: Chatral Rinpoche
  language: bo
  description: 'Texts by and about the great Dzogchen master Chatral Sangye Dorje
    (bya bral sangs rgyas rdo rje, 1913–2015):'
  volume:
    075eaba3b84842c3bc19d8be6a50861c:
      title: Spontaneous Advice Connected with a Prayer
      parent: Advice
    23c0f71360bf447297180af9bf2707f5:
      title: The Benefits of Saving Lives
      parent: Advice
    86efe75f5bff4a6da6031cd75db9e1d8:
      title: Words of Advice
      parent: Advice
    a59d40e2d93b4c3a8294a930d1bcbed2:
      title: 'The Rishi''s Maledictory Incantation: An Invocation of Wisdom Mind and
        Sacred Pledges for Reversing the Disturbances and Agitations of Dark Times
        In the Form of an Aspiration Prayer'
      parent: Aspiration Prayers
    f368ca9cbfd048d19b301f94391c3096:
      title: 'The Excellent Path of Supreme Great Bliss: A Prayer for Calling the
        Guru from Afar'
      parent: Calling the Guru from Afar
    2df1dd9117b0404e9ab8038ac96d1b73:
      title: A Profound and Concise Guru Yoga
      parent: Guru Yoga
    823c94118da54407925aad92b8e373f0:
      title: Introduction to The Excellent Path of Devotion
      parent: Introductions
    1d6c2aff783e4ec08c1ecb43f87b1d7a:
      title: Prayer for the Long Life of Namkhai Norbu Rinpoche
      parent: Long Life Prayers
    2a78f4cc394e4893a663889079311761:
      title: Prayer for the Long Life of Soktsé Rinpoche
      parent: Long Life Prayers
    d3bf8412dc0d49c792a577408c7fcfc7:
      title: A Guide to Uḍḍiyāna (Ujjain), Benglor
      parent: Pilgrimage
    4c4dc37d38cc4bdf90bd454a65115975:
      title: 'Melodious Tambura of Delight: A Guide to Māratika Cave, Supreme Site
        of Immortality'
      parent: Pilgrimage
    95e2ab4369124a7fa824a529a661fcab:
      title: Essence of All the Buddhas of Past, Present and Future
      parent: Prayers
    baff03a869524ca7a9af51b6f02e9d9a:
      title: 'The Condensed Essence: A Daily Practice of the Wrathful Guru Takhyung
        Barwa'
      parent: Sādhanas
    5163b9268ee34c68b95646a0107349a7:
      title: The Ritual of the Bodhisattva Vow According to the Tradition of Patrul
        Rinpoche
      parent: Vows & Commitments
created_at: '2022-02-28T22:42:38.133145'
last_modified_at: '2022-02-28T22:42:38.133148'
statistics:
  total_words: 12023
  total_non_words: 1237
quality:
  non_words_ratio: 0.1
